name: scqtl
channels:
- jdblischak
- bioconda
- conda-forge
- defaults
- anaconda
dependencies:
- bcftools
- bioconductor-annotationdbi
- bioconductor-biobase
- bioconductor-biocgenerics
- bioconductor-biomart
- bioconductor-edger
- bioconductor-iranges
- bioconductor-limma
- bioconductor-s4vectors
- bioconductor-scde=1.99.1
- fastqc
- htslib
- multiqc
- pysam
- samtools
- snakemake
- subread
- umi_tools
- verifybamid
- aioeasywebdav
- aiohttp
- appdirs
- asn1crypto
- async-timeout
- backports
- backports.functools_lru_cache
- backports.weakref
- biopython
- blas
- bleach
- bzip2
- ca-certificates
- cairo
- certifi
- cffi
- chardet
- click
- colormath
- configargparse
- cryptography
- curl
- cycler
- cython
- dbus
- decorator
- docopt
- docutils
- dropbox
- entrypoints
- expat
- filechunkio
- fontconfig
- freetype
- ftputil
- future
- gettext
- git
- git-lfs
- glib
- gmp
- graphite2
- gsl
- gst-plugins-base
- gstreamer
- harfbuzz
- html5lib
- icu
- idna
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jedi
- jinja2
- jpeg
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- krb5
- libffi
- libiconv
- libpng
- libsodium
- libssh2
- libtiff
- libxcb
- libxml2
- lzstring
- markdown
- markupsafe
- matplotlib
- mistune
- mmtf-python
- msgpack-python
- multidict
- nbconvert
- nbformat
- ncurses
- networkx
- nlopt
- notebook
- numpy
- olefile
- openblas
- openssl
- pandas
- pandoc=1.19.2
- pandocfilters
- pango
- paramiko
- pcre
- perl
- pexpect
- pickleshare
- pillow
- pip
- pixman
- prompt_toolkit
- protobuf
- psutil
- ptyprocess
- pyasn1
- pycparser
- pygments
- pynacl
- pyopenssl
- pyparsing
- pyqt
- pysftp
- pysocks
- python
- python-dateutil
- pytz
- pyyaml
- pyzmq
- qt
- qtconsole
- r-assertthat
- r-backports
- r-base
- r-base64enc
- r-bh
- r-bindr
- r-bindrcpp
- r-bit
- r-bit64
- r-bitops
- r-blob
- r-callr
- r-catools
- r-codetools
- r-colorramps
- r-colorspace
- r-cowplot
- r-curl
- r-data.table
- r-dbi
- r-dbplyr
- r-devtools
- r-dichromat
- r-digest
- r-doparallel
- r-dplyr
- r-dt
- r-evaluate
- r-flexmix=2.3_13
- r-foreach
- r-gdata
- r-getpass
- r-ggplot2
- r-git2r
- r-glue
- r-gplots
- r-gtable
- r-gtools
- r-heatmap3
- r-highr
- r-hms
- r-htmltools
- r-htmlwidgets
- r-httr
- r-iterators
- r-jsonlite
- r-kernsmooth
- r-knitr=1.20
- r-labeling
- r-lattice
- r-lazyeval
- r-lme4
- r-locfit
- r-magrittr
- r-markdown
- r-mass
- r-matrix
- r-memoise
- r-mgcv
- r-mime
- r-minqa
- r-munsell
- r-nlme
- r-nloptr
- r-openssl
- r-pbkrtest
- r-pkgconfig
- r-plogr
- r-plyr
- r-prettyunits
- r-progress
- r-purrr
- r-r.methodss3
- r-r.oo
- r-r.utils
- r-r6
- r-rcolorbrewer
- r-rcpp
- r-rcppeigen
- r-rcurl
- r-readr
- r-reshape2
- r-rlang
- r-rmarkdown=1.8
- r-rprojroot
- r-rsqlite
- r-rstudioapi
- r-scales
- r-stringi
- r-stringr
- r-testit
- r-tibble
- r-tidyr
- r-tidyselect
- r-viridislite
- r-whisker
- r-withr
- r-xml
- r-yaml
- ratelimiter
- readline
- regex
- reportlab
- requests
- rpy2
- scipy
- setuptools
- simplegeneric
- simplejson
- singledispatch
- sip
- six
- spectra
- sqlite
- terminado
- testpath
- tk
- tornado
- traitlets
- urllib3
- wcwidth
- webencodings
- werkzeug
- wheel
- widgetsnbextension
- wrapt
- xorg-libxau
- xorg-libxdmcp
- xz
- yaml
- yarl
- zeromq
- zlib
- bcrypt
- bokeh
- cloudpickle
- colorcet
- cudatoolkit
- cudnn
- dask
- dask-core
- distributed
- heapdict
- intel-openmp
- libgcc
- libgcc-ng
- libgfortran
- libprotobuf
- libstdcxx-ng
- locket
- mkl
- openjdk
- packaging
- partd
- sortedcontainers
- tblib
- tensorflow-gpu
- tensorflow-gpu-base
- tensorflow-tensorboard
- toolz
- wget
- zict
- bioconductor-variancepartition
- r-workflowr
- pip:
  - backports.functools-lru-cache
  - ipython-genutils
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - monotonic
  - nose
  - prompt-toolkit
  - pytabix
  - scikit-learn
  - sklearn
  - tensorflow
  - umi-tools
  - zifa
