# Conda configuration file to reproduce computing environment
#
# Create the conda environment:
#
# conda env create --file environment.yaml
#
# Update the conda environment:
#
# conda env update --file environment.yaml
#
# Activate the conda environment:
#
# source activate scqtl
#
# Deactivate the conda environment:
#
# source deactivate scqtl
#
# Resources:
#
# https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand
# https://bioconda.github.io
# https://anaconda.org/jdblischak/repo

name: scqtl
channels:
  - jdblischak
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bioconductor-biomart
  - bioconductor-edger
  - biopython
  - ipython
  - pandoc
  - pysam
  - python
  - r-base
  - r-callr
  - r-cowplot
  - r-devtools
  - r-dplyr
  - r-git2r
  - r-ggplot2
  - r-readr
  - r-rmarkdown >=0.9.6
  - r-rprojroot
  - r-rstudioapi
  - r-stringr >=1.2.0
  - r-testit
  - r-tidyr
  - r-whisker
  - r-yaml
  - rpy2
  - samtools
  - snakemake
  - subread
  - umi_tools
  - verifybamid
